SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS `ds_shop_order` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `order_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `uid` bigint NOT NULL,
  `item_count` int NOT NULL DEFAULT 0,
  `total_amount` decimal(12, 2) NOT NULL DEFAULT 0.00,
  `pay_points` decimal(12, 2) NOT NULL DEFAULT 0.00,
  `pay_status` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PAID',
  `paid_at` datetime NULL DEFAULT NULL,
  `product_summary` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_ds_shop_order_no` (`order_no`) USING BTREE,
  KEY `idx_ds_shop_order_uid` (`uid`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ds_shareholder_pool_record` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `biz_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `source_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `source_order_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `source_uid` bigint NULL DEFAULT NULL,
  `profit_amount` decimal(12, 2) NOT NULL DEFAULT 0.00,
  `pool_rate` decimal(10, 4) NOT NULL DEFAULT 0.0000,
  `pool_amount` decimal(12, 2) NOT NULL DEFAULT 0.00,
  `settle_month` varchar(7) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `settle_status` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDING',
  `settle_batch_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `settled_at` datetime NULL DEFAULT NULL,
  `occurred_at` datetime NOT NULL,
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_ds_shareholder_pool_record_biz_no` (`biz_no`) USING BTREE,
  KEY `idx_ds_shareholder_pool_record_month_status` (`settle_month`, `settle_status`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ds_shop_order_item` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `order_id` bigint NOT NULL,
  `order_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `uid` bigint NOT NULL,
  `shop_id` bigint NOT NULL,
  `product_id` bigint NOT NULL,
  `product_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `price_amount` decimal(12, 2) NOT NULL DEFAULT 0.00,
  `quantity` int NOT NULL DEFAULT 0,
  `line_amount` decimal(12, 2) NOT NULL DEFAULT 0.00,
  `paid_at` datetime NULL DEFAULT NULL,
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_ds_shop_order_item_order_id` (`order_id`) USING BTREE,
  KEY `idx_ds_shop_order_item_order_no` (`order_no`) USING BTREE,
  KEY `idx_ds_shop_order_item_uid_paid_at` (`uid`, `paid_at`) USING BTREE,
  KEY `idx_ds_shop_order_item_shop_paid_at` (`shop_id`, `paid_at`) USING BTREE,
  KEY `idx_ds_shop_order_item_product_id` (`product_id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ds_product_recommend_trace` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `trace_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `inviter_id` bigint NOT NULL,
  `invitee_id` bigint NOT NULL,
  `shop_id` bigint NOT NULL,
  `product_id` bigint NOT NULL,
  `recommend_scene` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'LINK',
  `recommend_status` tinyint NOT NULL DEFAULT 0,
  `recommended_at` datetime NOT NULL,
  `expire_at` datetime NULL DEFAULT NULL,
  `bind_order_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `bind_order_item_id` bigint NULL DEFAULT NULL,
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_ds_product_recommend_trace_no` (`trace_no`) USING BTREE,
  KEY `idx_ds_product_recommend_pair_product` (`inviter_id`, `invitee_id`, `product_id`) USING BTREE,
  KEY `idx_ds_product_recommend_invitee_status_time` (`invitee_id`, `recommend_status`, `recommended_at`) USING BTREE,
  KEY `idx_ds_product_recommend_bind_order_item` (`bind_order_item_id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ds_order_commission_split` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `split_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `order_id` bigint NOT NULL,
  `order_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `order_item_id` bigint NOT NULL,
  `shop_id` bigint NOT NULL,
  `gross_amount` decimal(12, 2) NOT NULL DEFAULT 0.00,
  `platform_rate` decimal(10, 4) NOT NULL DEFAULT 0.1000,
  `platform_amount` decimal(12, 2) NOT NULL DEFAULT 0.00,
  `reward_share_rate` decimal(10, 4) NOT NULL DEFAULT 0.2000,
  `reward_amount` decimal(12, 2) NOT NULL DEFAULT 0.00,
  `platform_net_amount` decimal(12, 2) NOT NULL DEFAULT 0.00,
  `settle_status` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDING',
  `settled_at` datetime NULL DEFAULT NULL,
  `occurred_at` datetime NOT NULL,
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_ds_order_commission_split_no` (`split_no`) USING BTREE,
  UNIQUE KEY `uk_ds_order_commission_item_id` (`order_item_id`) USING BTREE,
  KEY `idx_ds_order_commission_order_no` (`order_no`) USING BTREE,
  KEY `idx_ds_order_commission_shop_status` (`shop_id`, `settle_status`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ds_recommend_reward_record` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `reward_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `split_id` bigint NOT NULL,
  `order_id` bigint NOT NULL,
  `order_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `order_item_id` bigint NOT NULL,
  `trace_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `inviter_id` bigint NOT NULL,
  `invitee_id` bigint NOT NULL,
  `reward_rate` decimal(10, 4) NOT NULL DEFAULT 0.0200,
  `reward_amount` decimal(12, 2) NOT NULL DEFAULT 0.00,
  `grant_status` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDING',
  `grant_error` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `granted_at` datetime NULL DEFAULT NULL,
  `occurred_at` datetime NOT NULL,
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_ds_recommend_reward_no` (`reward_no`) USING BTREE,
  UNIQUE KEY `uk_ds_recommend_reward_item_inviter` (`order_item_id`, `inviter_id`) USING BTREE,
  KEY `idx_ds_recommend_reward_split_id` (`split_id`) USING BTREE,
  KEY `idx_ds_recommend_reward_inviter_status` (`inviter_id`, `grant_status`) USING BTREE,
  KEY `idx_ds_recommend_reward_invitee_time` (`invitee_id`, `occurred_at`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ds_platform_account` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `account_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'MAIN',
  `available_amount` decimal(14, 2) NOT NULL DEFAULT 0.00,
  `frozen_amount` decimal(14, 2) NOT NULL DEFAULT 0.00,
  `total_income_amount` decimal(14, 2) NOT NULL DEFAULT 0.00,
  `total_expense_amount` decimal(14, 2) NOT NULL DEFAULT 0.00,
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_ds_platform_account_code` (`account_code`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ds_platform_account_ledger` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `account_id` bigint NOT NULL,
  `change_type` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'INCOME',
  `amount` decimal(14, 2) NOT NULL DEFAULT 0.00,
  `balance_after` decimal(14, 2) NOT NULL DEFAULT 0.00,
  `biz_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `biz_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `order_id` bigint NULL DEFAULT NULL,
  `order_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `order_item_id` bigint NULL DEFAULT NULL,
  `split_id` bigint NULL DEFAULT NULL,
  `occurred_at` datetime NOT NULL,
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_ds_platform_ledger_biz_no` (`biz_no`) USING BTREE,
  KEY `idx_ds_platform_ledger_account_time` (`account_id`, `occurred_at`) USING BTREE,
  KEY `idx_ds_platform_ledger_order_item` (`order_item_id`) USING BTREE,
  KEY `idx_ds_platform_ledger_split_id` (`split_id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
